### ISSUE TITLE
can't open  "colab demo" and "Decoder Weights" in readme

### ISSUE THREAD

**Issue by luweishuang** [qywu/Chinese-GPT#3]
can't open links in "colab demo" and "Decoder Weights" in readme.md.  Also confused about "summarization", "origin_title", "third_title" in tutorials/Data Processing Example.ipynb means for?
Does it get from origin dataset such as "baike2018qa" directly and can you describ how to get this? thanks

**Comment by qywu** [comment]
Sorry, I forget to publicize the weights. They should be public now.

Also, in tutorials, those are some files from other projects. I will clean the repo soon and make it easier to use.
