### ISSUE TITLE
how to generate "model_state_epoch_62.th" in Decode.ipynb

### ISSUE THREAD

**Issue by luweishuang** [qywu/Chinese-GPT#4]
I firstly think "model_state_epoch_62.th" came from tutorials/Training.ipynb, but I just found it do load_state_dict inside. Seems I need do "Model Weights Conversion(*Optional).ipynb" first and then do "Training.ipynb". but there isn't a script to generate "model_state_epoch_62.th" in every scripts in tutorials. Can you give some brief introduce on hwo to generate model_state_epoch_62.th?

**Comment by qywu** [comment]
It is trained with data-parallel on 4 GPUs using another script. The weights can be directly loaded into the model. If you want to further pretrain it, you can consider Train.ipynb as a starting point.

**Comment by luweishuang** [comment]
I want consult some data process question too. Take baike2018qa as a example, it's format like {"qid":<qid>,"category":<category>,"title":<title>,"desc":<desc>,"answer":<answer>}
and I don't find summarization, origin_title, third_title col in it.  I want to know how do you get this content from origin corpus, like baike2018qa. thanks

**Comment by luweishuang** [comment]
I want consult some data process question too. Take baike2018qa as a example, it's format like {"qid":<qid>,"category":<category>,"title":<title>,"desc":<desc>,"answer":<answer>}
and I don't find summarization, origin_title, third_title col in it.  I want to know how do you get this content from origin corpus, like baike2018qa. thanks

**Comment by qywu** [comment]
Sorry for the late reply. I am a little busy recently. That script is actually from another project used to train a headline editing model. If you only want to train a language model, you can modify it to only train the decoder. I will find a time next month to organize this repo and have more clear tutorials.
